### ISSUE TITLE
The link to the dataset is now valid

### ISSUE THREAD

**Issue by JianHaoYin** [Ganzooo/LRSRN#1]
The link of 'Combined test dataset from Drive [Link]' is not available now.Could you please update the link?

**Comment by rlghksdbs** [comment]
It seems that the dataset that I uploaded now has been deleted. We will update it as soon as possible.

**Comment by rlghksdbs** [comment]
> 

It seems that the dataset that I uploaded now has been deleted. We will update it as soon as possible.

**Comment by rlghksdbs** [comment]
> The link of 'Combined test dataset from Drive [Link]' is not available now.Could you please update the link?


It seems that the dataset that I uploaded now has been deleted. We will update it as soon as possible.

**Comment by Ganzooo** [comment]
Sorry for the late response. We updated the combined dataset link in the Readme file.

**Comment by Ganzooo** [comment]
Issue resolved, closing.
