### ISSUE TITLE
The link for the model weights is broken

### ISSUE THREAD

**Issue by distoramos** [Ganzooo/LRSRN#4]
The link for the model weights is broken: https://wandb.ai/iilab/ECCV_MAI2020_SR

**Comment by rlghksdbs** [comment]
That link is our Wandb repositoty.

If you want to use wandb to track the loss of training or the saturation of the PSNR, you can replace the wandb control with your account, such as line 71 of train.py 

" run_log_wandb = wandb.init(entity="iilab", project='Realt_Time_Super_Resolution'"

Thank you for your interest in our project.

**Comment by distoramos** [comment]
What I was looking for is the model weights '.pth' to repro the results in the paper and I am not seeing any links. Is it possible to share the model weights?
Thank and appreciate your prompt response

**Comment by rlghksdbs** [comment]
I understand your request.

We didn't release the weight file when we released the code.

I can't immediately confirm if this is the exact weight file that produces the performance we published in the paper.

However, if you need to use it in a hurry, we have provided links below to weights that we infer will yield the performance shown in the paper.

Track1 (X2) : https://drive.google.com/drive/folders/1A45mRj1CasabLpy3ie8JxZoue5g2J-Tl?usp=sharing
Track2 (X3) : https://drive.google.com/file/d/1kcNaB-kN_d5TlHTQoJ5-_8_5seLiq-L9/view?usp=sharing

For Track1 (X2), we have 3 candidates that we submitted for the NTIRE competition, and I think final_submission_x2_Candidate1.zip is probably the right file.

I will check both X2 and X3 later and put them in the final code.

Thanks

**Comment by distoramos** [comment]
Thank you for sharing.
